//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargoTakipOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KargoBilgi
    {
        public int ID { get; set; }
        public string Barkod { get; set; }
        public Nullable<int> Musteri_ID { get; set; }
        public string Alici_Ad { get; set; }
        public string Alici_Soyad { get; set; }
        public string Alici_Tel { get; set; }
        public string Alici_Adres { get; set; }
        public string Gonderim_Tarih { get; set; }
        public string Durum { get; set; }
        public string Icerik { get; set; }
        public string Hassaslik { get; set; }
    }
}
